remote_theme: just-the-docs/just-the-docs

title: trappsec
description: application-layer deception framework
url: "https://trappsec.dev"

search_enabled: true
heading_anchors: true

aux_links:
  "GitHub": "https://github.com/trappsec-dev/trappsec"